version: '3.8'
services:
  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  flyway:
    image: flyway/flyway:8
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql_versions:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${PWD}/prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest-ubuntu
    volumes:
      - ${PWD}/prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ${PWD}/prometheus-grafana/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    links:
      - prometheus
