server:
  port: 8081

spring:
  application:
    name: api-books
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    password: test
    username: test
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    datasources:
      default:
        locations: classpath:db/migration

info:
  app:
    name: project.name
    description: project.description
    version: project.version
    encoding: project.encoding
    java:
      version: java.version

management:
  endpoints:
    shutdown:
      enable: true
    health:
      show-details: always
    web:
      exposure:
        include: health, info, prometheus, metrics

logging:
  level:
    root: WARN
    com:
      infnet:
        books: TRACE