server:
  port: 8089

spring:
  application:
    name: booksapi
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    password: test
    username: test
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    datasources:
      default:
        locations: classpath:db/migration
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411

info:
  app:
    name: project.name
    description: project.description
    version: project.version
    encoding: project.encoding
    java:
      version: java.version

management:
  metrics:
    enable:
      jvm: true
    tags:
      application: booksapi
  endpoints:
    shutdown:
      enable: true
    health:
      show-details: always
    web:
      exposure:
        include: health, info, prometheus, metrics

logging:
  level:
    root: WARN
    com:
      infnet:
        books: TRACE