company = "alexandrequeirozcloud"
prefix = "alexandrequeiroz"
environment = "dev"
location = "northeurope"
description = "Deploy a PostgreSQL Server"
owner = "Alexandre Queiroz"

azure-subscription-id = "complete-me"
azure-client-id = "complete-me"
azure-client-secret = "complete-me"
azure-tenant-id = "complete-me"

postgresql-admin-login = "alexandreadmin"
postgresql-admin-password = "4b4c4t3@$"
postgresql-version = "12"
postgresql-sku-name = "B_Gen5_1"
postgresql-storage = "5120"
